services:
  description-backend:
    container_name: description-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - API_URL=http://192.168.1.34:1234/v1 # CHANGE THIS TO YOUR LM API URL
      - API_KEY=lm-studio # CHANGE THIS TO YOUR LM API KEY
    volumes:
      - ./backend:/app
    networks:
      - media-network
    restart: unless-stopped

  description-frontend:
    container_name: description-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - BACKEND_URL=http://description-backend:3002  # Uses Docker's internal networking
    depends_on:
      - description-backend
    volumes:
      - ./frontend:/app
    networks:
      - media-network
    restart: unless-stopped

networks:
  media-network:
    driver: bridge